# Generated by Django 4.2.4 on 2023-11-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0002_clasemodelo_delete_frase_delete_idioma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('clasemodelo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bases.clasemodelo')),
                ('descripcion', models.CharField(help_text='Descripcion de la Categoria', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
            bases=('bases.clasemodelo',),
        ),
    ]
